name=input("plz enter your name")
branch=input("plz inpur your branch")
gender=input("plz inpur your gender")
clgname=input("plz inpur your clgname")
age=input("plz inpur your age")
print("name-",name)
print("branch-",branch)
print("gender-",gender)
print("collegename-",clgname)
print("age-",age)
