player_1=int(input("enter the run socred by player1 after facing 60 balls"))
player_2=int(input("enter the run socred by player2 after facing 60 balls"))
player_3=int(input("enter the run socred by player3 after facing 60 balls"))
strikerate_1=((player_1)*100)/(60)
strikerate_2=((player_2)*100)/(60)
strikerate_3=((player_3)*100)/(60)
print("strike rate of player1:",strikerate_1)
print("strike rate of player2:",strikerate_2)
print("strike rate of player3:",strikerate_3)
print("total runs scored by  player1 after facing 60 balls more:",(player_1)*2)
print("total runs scored by  player2 after facing 60 balls more:",(player_2)*2)
print("total runs scored by  player3 after facing 60 balls more:",(player_3)*2)
print("no of sixes hit by player1 after facing 60 balls:",(player_1)//6)
print("no of sixes hit by player2 after facing 60 balls:",(player_2)//6)
print("no of sixes hit by player3 after facing 60 balls:",(player_3)//6)
